export const workspaceCopy = {
  de: { account:'Mein Konto', accountLead:'Ihre Besuche, Präferenzen und sicheren Zugänge.', workspaces:'Arbeitsbereiche', choose:'Wählen Sie eine Filiale und Ihre Aufgabe.', noWorkspace:'Noch kein Teamzugang', noWorkspaceLead:'Eine Einladung des Restaurant-Managements erscheint nach Annahme hier.', profile:'Persönliche Angaben', appearance:'Darstellung & Sprache', security:'Sicherheit', verified:'E-Mail bestätigt', branch:'Filiale', enter:'Öffnen', customer:'Gastprofil', waiter:'Service & Gastraum', kitchen:'Küche', cashier:'Kasse', delivery:'Auslieferung', manager:'Management', superadmin:'Systemverwaltung', forbidden:'Kein Zugriff', forbiddenLead:'Dieser Bereich gehört nicht zu Ihren aktuellen Rollen.', backAccount:'Zum Konto', coming:'Dieser sichere Arbeitsbereich ist bereit. Die operativen Werkzeuge folgen im nächsten Umsetzungsschritt.', signOut:'Abmelden' },
  en: { account:'My account', accountLead:'Your visits, preferences and secure access.', workspaces:'Workspaces', choose:'Choose a branch and the role you are working in.', noWorkspace:'No team access yet', noWorkspaceLead:'An invitation from restaurant management will appear here after you accept it.', profile:'Personal details', appearance:'Appearance & language', security:'Security', verified:'Email verified', branch:'Branch', enter:'Open', customer:'Guest profile', waiter:'Service & dining room', kitchen:'Kitchen', cashier:'Cashier', delivery:'Delivery', manager:'Management', superadmin:'System administration', forbidden:'Access unavailable', forbiddenLead:'This area is not included in your current roles.', backAccount:'Back to account', coming:'This secure workspace is ready. Operational tools arrive in the next implementation slice.', signOut:'Sign out' },
  fa: { account:'حساب من', accountLead:'بازدیدها، ترجیحات و دسترسی‌های امن شما.', workspaces:'فضاهای کاری', choose:'شعبه و نقشی را که با آن کار می‌کنید انتخاب کنید.', noWorkspace:'هنوز دسترسی تیمی ندارید', noWorkspaceLead:'دعوت مدیریت رستوران پس از پذیرش در اینجا نمایش داده می‌شود.', profile:'اطلاعات شخصی', appearance:'ظاهر و زبان', security:'امنیت', verified:'ایمیل تأیید شده', branch:'شعبه', enter:'ورود', customer:'پروفایل مشتری', waiter:'گارسون و سالن', kitchen:'آشپزخانه', cashier:'صندوق', delivery:'ارسال', manager:'مدیریت شعبه', superadmin:'مدیریت کل سیستم', forbidden:'دسترسی مجاز نیست', forbiddenLead:'این بخش در نقش‌های فعلی شما قرار ندارد.', backAccount:'بازگشت به حساب', coming:'فضای کاری امن آماده است. ابزارهای عملیاتی در مرحله اجرایی بعدی فعال می‌شوند.', signOut:'خروج از حساب' },
  ar: { account:'حسابي', accountLead:'زياراتك وتفضيلاتك وصلاحياتك الآمنة.', workspaces:'مساحات العمل', choose:'اختر الفرع والدور الذي تعمل به.', noWorkspace:'لا يوجد وصول للفريق بعد', noWorkspaceLead:'ستظهر دعوة إدارة المطعم هنا بعد قبولها.', profile:'البيانات الشخصية', appearance:'المظهر واللغة', security:'الأمان', verified:'تم تأكيد البريد', branch:'الفرع', enter:'فتح', customer:'ملف العميل', waiter:'الخدمة والصالة', kitchen:'المطبخ', cashier:'الصندوق', delivery:'التوصيل', manager:'إدارة الفرع', superadmin:'إدارة النظام', forbidden:'الوصول غير متاح', forbiddenLead:'هذه المنطقة ليست ضمن أدوارك الحالية.', backAccount:'العودة للحساب', coming:'مساحة العمل الآمنة جاهزة. ستصل الأدوات التشغيلية في مرحلة التنفيذ التالية.', signOut:'تسجيل الخروج' },
};

export const rolePaths = {
  waiter: 'waiter', kitchen: 'kitchen', cashier: 'cashier', delivery: 'delivery', manager: 'owner', superadmin: 'owner',
};
